### ISSUE TITLE
Nextjs API getSession() is not working.

### ISSUE THREAD

**Issue by togisoft** [better-auth/better-auth#823] opened 2024-12-08 17:10 UTC
I do getSession with Nextjs App router API, but when I do fetch, I get a 401.   Why?.I couldn't find a solution to this.

```ts
/**
 * GET API Route: Get all colors.
 */
async function getColors(req: NextRequest): Promise<NextResponse> {
    await connectToDatabase();

    try {
        const session = await auth.api.getSession({
            headers: await headers(),
        })


        if (!session) {
            return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
        }

        if (session.user.role !== "admin") {
            return NextResponse.json({ message: "Forbidden: Admins only" }, { status: 403 });
        }

        const colors = await ColorModel.find()
            .populate("name")
            .lean();

        return NextResponse.json(colors, { status: 200 });
    } catch (error: any) {
        console.error("Error fetch colors", error.message);
        return NextResponse.json(
            { error: { message: error.message || "An unkown error occurred!" } },
            { status: 400 }
        )
    }
}

export const GET = getColors;
```

```ts
import { $fetch, $fetchBetter } from "@/lib/fetch";
import { Color } from "@/types/catalog/attributes";
import { LocalesData } from "@/types/locales-data";
import Client from "./client";

export default async function Page() {
    const [locales, colors] = await Promise.all([
        $fetchBetter<LocalesData>("/locales"), // Locales API'si
        $fetch<Color[] | null>("/catalog/attributes/colors"), // Categories API'si
    ]);

    return (
        <Client params={{
            localesData: locales.data!
        }} />
    );
}
```

**Comment by Bekacru** [comment] 2024-12-08 17:24
try to see if `headers` have `better_auth` cookies. Also you can directly pass the headers from the request. `req.headers`

**Comment by togisoft** [comment] 2024-12-08 18:52
When I added the headers like this it worked.
```ts
import { $fetch } from "@/lib/fetch";
import { LocalesData } from "@/types/locales-data";
import Client from "./client";
import { Color } from "@/types/catalog/attributes";
import { headers } from "next/headers";

export default async function Page() {
    const [locales, colors] = await Promise.all([
        $fetch<LocalesData>("/locales"), // Locales API'si
        $fetch<Color[] | null>("/catalog/attributes/colors", {
            headers: await headers() as any
        })
    ]);
    return (
        <Client params={{
            localesData: locales.data!,
            colors: colors.data
        }} />
    );
}
```

**Comment by Bekacru** [comment] 2024-12-14 05:19
that's the intended behavior closing this as resovled

**Closed by Bekacru** 2024-12-14 05:19 UTC
